from sqlalchemy.orm import Session
from app.models.student import Student

def get_all_students(db: Session, filters: dict):
    """
    Retrieves all students from the database with optional filtering.
    Supports filtering by major, semester, and active status.
    """
    query = db.query(Student)

# Apply filters dynamically if they are provided in the request
    if filters.get("major"):
        query = query.filter(Student.major == filters["major"])
    if filters.get("semester"):
        query = query.filter(Student.semester == filters["semester"])
    if filters.get("is_active") is not None:
        query = query.filter(Student.is_active == filters["is_active"])

    return query.all()

def get_student_by_id(db: Session, student_id: int):
    """
    Fetches a single student record by its primary key (ID).
    Returns None if the student does not exist.
    """
    return db.query(Student).filter(Student.id == student_id).first()

def get_student_by_email(db: Session, email: str):
    """
    Finds a student by their email address. 
    Used to validate uniqueness before creating new records.
    """
    return db.query(Student).filter(Student.email == email).first()

def create_student(db: Session, data: dict):
    """
    Adds a new student to the database.
    The 'data' dictionary is unpacked to initialize the Student model.
    """
    student = Student(**data)
    db.add(student)
    db.commit() # Save changes to the database
    db.refresh(student) # Refresh the object with the ID generated by the DB
    return student

def update_student(db: Session, student: Student, data: dict):
    """
    Updates an existing student's attributes.
    Supports both partial (PATCH) and full (PUT) updates.
    """
    for key, value in data.items():
        setattr(student, key, value)
    db.commit()
    db.refresh(student)
    return student

def soft_delete_student(db: Session, student: Student):
    """
    Performs a logical deletion by setting 'is_active' to False.
    This ensures data persistence for academic history while hiding it from active lists.
    """
    student.is_active = False
    db.commit()
